/*
 * Copyright (c) 2023 Trail of Bits, Inc.
 */

// This file is auto-generated.

#include <pasta/AST/AST.h>
#include <pasta/AST/Attr.h>
#include <pasta/AST/Decl.h>
#include <pasta/AST/Stmt.h>
#include <pasta/AST/Type.h>

#include "../Bindings.h"

namespace pasta {
namespace nb = nanobind;

void RegisterCXXRecordDecl(nb::module_ &m) {
  nb::class_<CXXRecordDecl, RecordDecl>(m, "CXXRecordDecl")
    .def("__hash__", [](const CXXRecordDecl &decl) { return reinterpret_cast<intptr_t>(decl.RawDecl()); })
    .def("__eq__", [](const Decl &a, const Decl &b) { return a.RawDecl() == b.RawDecl(); })
    .def_prop_ro("size_without_virtual_bases", &CXXRecordDecl::SizeWithoutVirtualBases)
    .def_prop_ro("primary_base", &CXXRecordDecl::PrimaryBase)
    .def_prop_ro("has_own_virtual_function_table_pointer", &CXXRecordDecl::HasOwnVirtualFunctionTablePointer)
    .def_prop_ro("has_extendable_virtual_function_table_pointer", &CXXRecordDecl::HasExtendableVirtualFunctionTablePointer)
    .def_prop_ro("has_virtual_base_table_pointer", &CXXRecordDecl::HasVirtualBaseTablePointer)
    .def_prop_ro("has_own_virtual_base_table_pointer", &CXXRecordDecl::HasOwnVirtualBaseTablePointer)
    .def_prop_ro("allow_const_default_initializer", &CXXRecordDecl::AllowConstDefaultInitializer)
    .def_prop_ro("bases", &CXXRecordDecl::Bases)
    .def_prop_ro("calculate_inheritance_model", &CXXRecordDecl::CalculateInheritanceModel)
    .def_prop_ro("constructors", &CXXRecordDecl::Constructors)
    .def_prop_ro("defaulted_copy_constructor_is_deleted", &CXXRecordDecl::DefaultedCopyConstructorIsDeleted)
    .def_prop_ro("defaulted_default_constructor_is_constexpr", &CXXRecordDecl::DefaultedDefaultConstructorIsConstexpr)
    .def_prop_ro("defaulted_destructor_is_constexpr", &CXXRecordDecl::DefaultedDestructorIsConstexpr)
    .def_prop_ro("defaulted_destructor_is_deleted", &CXXRecordDecl::DefaultedDestructorIsDeleted)
    .def_prop_ro("defaulted_move_constructor_is_deleted", &CXXRecordDecl::DefaultedMoveConstructorIsDeleted)
    .def_prop_ro("friends", &CXXRecordDecl::Friends)
    .def_prop_ro("canonical_declaration", &CXXRecordDecl::CanonicalDeclaration)
    .def_prop_ro("definition", &CXXRecordDecl::Definition)
    .def_prop_ro("dependent_lambda_call_operator", &CXXRecordDecl::DependentLambdaCallOperator)
    .def_prop_ro("described_class_template", &CXXRecordDecl::DescribedClassTemplate)
    .def_prop_ro("destructor", &CXXRecordDecl::Destructor)
    .def_prop_ro("device_lambda_mangling_number", &CXXRecordDecl::DeviceLambdaManglingNumber)
    .def_prop_ro("generic_lambda_template_parameter_list", &CXXRecordDecl::GenericLambdaTemplateParameterList)
    .def_prop_ro("instantiated_from_member_class", &CXXRecordDecl::InstantiatedFromMemberClass)
    .def_prop_ro("lambda_call_operator", &CXXRecordDecl::LambdaCallOperator)
    .def_prop_ro("lambda_capture_default", &CXXRecordDecl::LambdaCaptureDefault)
    .def_prop_ro("lambda_context_declaration", &CXXRecordDecl::LambdaContextDeclaration)
    .def_prop_ro("lambda_dependency_kind", &CXXRecordDecl::LambdaDependencyKind)
    .def_prop_ro("lambda_explicit_template_parameters", &CXXRecordDecl::LambdaExplicitTemplateParameters)
    .def_prop_ro("lambda_index_in_context", &CXXRecordDecl::LambdaIndexInContext)
    .def_prop_ro("lambda_mangling_number", &CXXRecordDecl::LambdaManglingNumber)
    .def_prop_ro("ms_inheritance_model", &CXXRecordDecl::MSInheritanceModel)
    .def_prop_ro("ms_vtor_disp_mode", &CXXRecordDecl::MSVtorDispMode)
    .def_prop_ro("most_recent_declaration", &CXXRecordDecl::MostRecentDeclaration)
    .def_prop_ro("num_bases", &CXXRecordDecl::NumBases)
    .def_prop_ro("num_virtual_bases", &CXXRecordDecl::NumVirtualBases)
    .def_prop_ro("odr_hash", &CXXRecordDecl::ODRHash)
    .def_prop_ro("previous_declaration", &CXXRecordDecl::PreviousDeclaration)
    .def_prop_ro("template_instantiation_pattern", &CXXRecordDecl::TemplateInstantiationPattern)
    .def_prop_ro("template_specialization_kind", &CXXRecordDecl::TemplateSpecializationKind)
    .def_prop_ro("has_any_dependent_bases", &CXXRecordDecl::HasAnyDependentBases)
    .def_prop_ro("has_constexpr_default_constructor", &CXXRecordDecl::HasConstexprDefaultConstructor)
    .def_prop_ro("has_constexpr_destructor", &CXXRecordDecl::HasConstexprDestructor)
    .def_prop_ro("has_constexpr_non_copy_move_constructor", &CXXRecordDecl::HasConstexprNonCopyMoveConstructor)
    .def_prop_ro("has_copy_assignment_with_const_parameter", &CXXRecordDecl::HasCopyAssignmentWithConstParameter)
    .def_prop_ro("has_copy_constructor_with_const_parameter", &CXXRecordDecl::HasCopyConstructorWithConstParameter)
    .def_prop_ro("has_default_constructor", &CXXRecordDecl::HasDefaultConstructor)
    .def_prop_ro("has_definition", &CXXRecordDecl::HasDefinition)
    .def_prop_ro("has_direct_fields", &CXXRecordDecl::HasDirectFields)
    .def_prop_ro("has_friends", &CXXRecordDecl::HasFriends)
    .def_prop_ro("has_in_class_initializer", &CXXRecordDecl::HasInClassInitializer)
    .def_prop_ro("has_inherited_assignment", &CXXRecordDecl::HasInheritedAssignment)
    .def_prop_ro("has_inherited_constructor", &CXXRecordDecl::HasInheritedConstructor)
    .def_prop_ro("has_initializer_method", &CXXRecordDecl::HasInitializerMethod)
    .def_prop_ro("has_irrelevant_destructor", &CXXRecordDecl::HasIrrelevantDestructor)
    .def_prop_ro("has_known_lambda_internal_linkage", &CXXRecordDecl::HasKnownLambdaInternalLinkage)
    .def_prop_ro("has_move_assignment", &CXXRecordDecl::HasMoveAssignment)
    .def_prop_ro("has_move_constructor", &CXXRecordDecl::HasMoveConstructor)
    .def_prop_ro("has_mutable_fields", &CXXRecordDecl::HasMutableFields)
    .def_prop_ro("has_non_literal_type_fields_or_bases", &CXXRecordDecl::HasNonLiteralTypeFieldsOrBases)
    .def_prop_ro("has_non_trivial_copy_assignment", &CXXRecordDecl::HasNonTrivialCopyAssignment)
    .def_prop_ro("has_non_trivial_copy_constructor", &CXXRecordDecl::HasNonTrivialCopyConstructor)
    .def_prop_ro("has_non_trivial_copy_constructor_for_call", &CXXRecordDecl::HasNonTrivialCopyConstructorForCall)
    .def_prop_ro("has_non_trivial_default_constructor", &CXXRecordDecl::HasNonTrivialDefaultConstructor)
    .def_prop_ro("has_non_trivial_destructor", &CXXRecordDecl::HasNonTrivialDestructor)
    .def_prop_ro("has_non_trivial_destructor_for_call", &CXXRecordDecl::HasNonTrivialDestructorForCall)
    .def_prop_ro("has_non_trivial_move_assignment", &CXXRecordDecl::HasNonTrivialMoveAssignment)
    .def_prop_ro("has_non_trivial_move_constructor", &CXXRecordDecl::HasNonTrivialMoveConstructor)
    .def_prop_ro("has_non_trivial_move_constructor_for_call", &CXXRecordDecl::HasNonTrivialMoveConstructorForCall)
    .def_prop_ro("has_private_fields", &CXXRecordDecl::HasPrivateFields)
    .def_prop_ro("has_protected_fields", &CXXRecordDecl::HasProtectedFields)
    .def_prop_ro("has_simple_copy_assignment", &CXXRecordDecl::HasSimpleCopyAssignment)
    .def_prop_ro("has_simple_copy_constructor", &CXXRecordDecl::HasSimpleCopyConstructor)
    .def_prop_ro("has_simple_destructor", &CXXRecordDecl::HasSimpleDestructor)
    .def_prop_ro("has_simple_move_assignment", &CXXRecordDecl::HasSimpleMoveAssignment)
    .def_prop_ro("has_simple_move_constructor", &CXXRecordDecl::HasSimpleMoveConstructor)
    .def_prop_ro("has_trivial_copy_assignment", &CXXRecordDecl::HasTrivialCopyAssignment)
    .def_prop_ro("has_trivial_copy_constructor", &CXXRecordDecl::HasTrivialCopyConstructor)
    .def_prop_ro("has_trivial_copy_constructor_for_call", &CXXRecordDecl::HasTrivialCopyConstructorForCall)
    .def_prop_ro("has_trivial_default_constructor", &CXXRecordDecl::HasTrivialDefaultConstructor)
    .def_prop_ro("has_trivial_destructor", &CXXRecordDecl::HasTrivialDestructor)
    .def_prop_ro("has_trivial_destructor_for_call", &CXXRecordDecl::HasTrivialDestructorForCall)
    .def_prop_ro("has_trivial_move_assignment", &CXXRecordDecl::HasTrivialMoveAssignment)
    .def_prop_ro("has_trivial_move_constructor", &CXXRecordDecl::HasTrivialMoveConstructor)
    .def_prop_ro("has_trivial_move_constructor_for_call", &CXXRecordDecl::HasTrivialMoveConstructorForCall)
    .def_prop_ro("has_uninitialized_reference_member", &CXXRecordDecl::HasUninitializedReferenceMember)
    .def_prop_ro("has_user_declared_constructor", &CXXRecordDecl::HasUserDeclaredConstructor)
    .def_prop_ro("has_user_declared_copy_assignment", &CXXRecordDecl::HasUserDeclaredCopyAssignment)
    .def_prop_ro("has_user_declared_copy_constructor", &CXXRecordDecl::HasUserDeclaredCopyConstructor)
    .def_prop_ro("has_user_declared_destructor", &CXXRecordDecl::HasUserDeclaredDestructor)
    .def_prop_ro("has_user_declared_move_assignment", &CXXRecordDecl::HasUserDeclaredMoveAssignment)
    .def_prop_ro("has_user_declared_move_constructor", &CXXRecordDecl::HasUserDeclaredMoveConstructor)
    .def_prop_ro("has_user_declared_move_operation", &CXXRecordDecl::HasUserDeclaredMoveOperation)
    .def_prop_ro("has_user_provided_default_constructor", &CXXRecordDecl::HasUserProvidedDefaultConstructor)
    .def_prop_ro("has_variant_members", &CXXRecordDecl::HasVariantMembers)
    .def_prop_ro("implicit_copy_assignment_has_const_parameter", &CXXRecordDecl::ImplicitCopyAssignmentHasConstParameter)
    .def_prop_ro("implicit_copy_constructor_has_const_parameter", &CXXRecordDecl::ImplicitCopyConstructorHasConstParameter)
    .def_prop_ro("is_abstract", &CXXRecordDecl::IsAbstract)
    .def_prop_ro("is_aggregate", &CXXRecordDecl::IsAggregate)
    .def_prop_ro("is_any_destructor_no_return", &CXXRecordDecl::IsAnyDestructorNoReturn)
    .def_prop_ro("is_c_like", &CXXRecordDecl::IsCLike)
    .def_prop_ro("is_cxx11_standard_layout", &CXXRecordDecl::IsCXX11StandardLayout)
    .def_prop_ro("is_dependent_lambda", &CXXRecordDecl::IsDependentLambda)
    .def_prop_ro("is_dynamic_class", &CXXRecordDecl::IsDynamicClass)
    .def_prop_ro("is_effectively_final", &CXXRecordDecl::IsEffectivelyFinal)
    .def_prop_ro("is_empty", &CXXRecordDecl::IsEmpty)
    .def_prop_ro("is_generic_lambda", &CXXRecordDecl::IsGenericLambda)
    .def_prop_ro("is_interface_like", &CXXRecordDecl::IsInterfaceLike)
    .def_prop_ro("is_lambda", &CXXRecordDecl::IsLambda)
    .def_prop_ro("is_literal", &CXXRecordDecl::IsLiteral)
    .def_prop_ro("is_local_class", &CXXRecordDecl::IsLocalClass)
    .def_prop_ro("is_never_dependent_lambda", &CXXRecordDecl::IsNeverDependentLambda)
    .def_prop_ro("is_pod", &CXXRecordDecl::IsPOD)
    .def_prop_ro("is_parsing_base_specifiers", &CXXRecordDecl::IsParsingBaseSpecifiers)
    .def_prop_ro("is_polymorphic", &CXXRecordDecl::IsPolymorphic)
    .def_prop_ro("is_standard_layout", &CXXRecordDecl::IsStandardLayout)
    .def_prop_ro("is_structural", &CXXRecordDecl::IsStructural)
    .def_prop_ro("is_trivial", &CXXRecordDecl::IsTrivial)
    .def_prop_ro("is_trivially_copyable", &CXXRecordDecl::IsTriviallyCopyable)
    .def_prop_ro("lambda_is_default_constructible_and_assignable", &CXXRecordDecl::LambdaIsDefaultConstructibleAndAssignable)
    .def_prop_ro("may_be_abstract", &CXXRecordDecl::MayBeAbstract)
    .def_prop_ro("may_be_dynamic_class", &CXXRecordDecl::MayBeDynamicClass)
    .def_prop_ro("may_be_non_dynamic_class", &CXXRecordDecl::MayBeNonDynamicClass)
    .def_prop_ro("methods", &CXXRecordDecl::Methods)
    .def_prop_ro("needs_implicit_copy_assignment", &CXXRecordDecl::NeedsImplicitCopyAssignment)
    .def_prop_ro("needs_implicit_copy_constructor", &CXXRecordDecl::NeedsImplicitCopyConstructor)
    .def_prop_ro("needs_implicit_default_constructor", &CXXRecordDecl::NeedsImplicitDefaultConstructor)
    .def_prop_ro("needs_implicit_destructor", &CXXRecordDecl::NeedsImplicitDestructor)
    .def_prop_ro("needs_implicit_move_assignment", &CXXRecordDecl::NeedsImplicitMoveAssignment)
    .def_prop_ro("needs_implicit_move_constructor", &CXXRecordDecl::NeedsImplicitMoveConstructor)
    .def_prop_ro("needs_overload_resolution_for_copy_assignment", &CXXRecordDecl::NeedsOverloadResolutionForCopyAssignment)
    .def_prop_ro("needs_overload_resolution_for_copy_constructor", &CXXRecordDecl::NeedsOverloadResolutionForCopyConstructor)
    .def_prop_ro("needs_overload_resolution_for_destructor", &CXXRecordDecl::NeedsOverloadResolutionForDestructor)
    .def_prop_ro("needs_overload_resolution_for_move_assignment", &CXXRecordDecl::NeedsOverloadResolutionForMoveAssignment)
    .def_prop_ro("needs_overload_resolution_for_move_constructor", &CXXRecordDecl::NeedsOverloadResolutionForMoveConstructor)
    .def_prop_ro("null_field_offset_is_zero", &CXXRecordDecl::NullFieldOffsetIsZero)
    .def_prop_ro("virtual_bases", &CXXRecordDecl::VirtualBases);
}
} // namespace pasta
