/*
 * Copyright (c) 2023 Trail of Bits, Inc.
 */

// This file is auto-generated.

#include <pasta/AST/AST.h>
#include <pasta/AST/Attr.h>
#include <pasta/AST/Decl.h>
#include <pasta/AST/Stmt.h>
#include <pasta/AST/Type.h>

#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace pasta {
namespace py = pybind11;

void RegisterCXXRecordDecl(py::module_ &m) {
  py::class_<CXXRecordDecl, RecordDecl>(m, "CXXRecordDecl")
    .def("__hash__", [](const CXXRecordDecl& decl) { return (intptr_t)decl.RawDecl(); })
    .def("__eq__", [](const Decl& a, const Decl& b) { return a.RawDecl() == b.RawDecl(); })
    .def_property_readonly("allow_const_default_initializer", &CXXRecordDecl::AllowConstDefaultInitializer)
    .def_property_readonly("bases", &CXXRecordDecl::Bases)
    .def_property_readonly("calculate_inheritance_model", &CXXRecordDecl::CalculateInheritanceModel)
    .def_property_readonly("constructors", &CXXRecordDecl::Constructors)
    .def_property_readonly("defaulted_copy_constructor_is_deleted", &CXXRecordDecl::DefaultedCopyConstructorIsDeleted)
    .def_property_readonly("defaulted_default_constructor_is_constexpr", &CXXRecordDecl::DefaultedDefaultConstructorIsConstexpr)
    .def_property_readonly("defaulted_destructor_is_constexpr", &CXXRecordDecl::DefaultedDestructorIsConstexpr)
    .def_property_readonly("defaulted_destructor_is_deleted", &CXXRecordDecl::DefaultedDestructorIsDeleted)
    .def_property_readonly("defaulted_move_constructor_is_deleted", &CXXRecordDecl::DefaultedMoveConstructorIsDeleted)
    .def_property_readonly("friends", &CXXRecordDecl::Friends)
    .def_property_readonly("canonical_declaration", &CXXRecordDecl::CanonicalDeclaration)
    .def_property_readonly("definition", &CXXRecordDecl::Definition)
    .def_property_readonly("dependent_lambda_call_operator", &CXXRecordDecl::DependentLambdaCallOperator)
    .def_property_readonly("described_class_template", &CXXRecordDecl::DescribedClassTemplate)
    .def_property_readonly("destructor", &CXXRecordDecl::Destructor)
    .def_property_readonly("device_lambda_mangling_number", &CXXRecordDecl::DeviceLambdaManglingNumber)
    .def_property_readonly("generic_lambda_template_parameter_list", &CXXRecordDecl::GenericLambdaTemplateParameterList)
    .def_property_readonly("instantiated_from_member_class", &CXXRecordDecl::InstantiatedFromMemberClass)
    .def_property_readonly("lambda_call_operator", &CXXRecordDecl::LambdaCallOperator)
    .def_property_readonly("lambda_capture_default", &CXXRecordDecl::LambdaCaptureDefault)
    .def_property_readonly("lambda_context_declaration", &CXXRecordDecl::LambdaContextDeclaration)
    .def_property_readonly("lambda_dependency_kind", &CXXRecordDecl::LambdaDependencyKind)
    .def_property_readonly("lambda_explicit_template_parameters", &CXXRecordDecl::LambdaExplicitTemplateParameters)
    .def_property_readonly("lambda_mangling_number", &CXXRecordDecl::LambdaManglingNumber)
    .def_property_readonly("lambda_type", &CXXRecordDecl::LambdaType)
    .def_property_readonly("ms_inheritance_model", &CXXRecordDecl::MSInheritanceModel)
    .def_property_readonly("ms_vtor_disp_mode", &CXXRecordDecl::MSVtorDispMode)
    .def_property_readonly("most_recent_declaration", &CXXRecordDecl::MostRecentDeclaration)
    .def_property_readonly("most_recent_non_injected_declaration", &CXXRecordDecl::MostRecentNonInjectedDeclaration)
    .def_property_readonly("num_bases", &CXXRecordDecl::NumBases)
    .def_property_readonly("num_virtual_bases", &CXXRecordDecl::NumVirtualBases)
    .def_property_readonly("odr_hash", &CXXRecordDecl::ODRHash)
    .def_property_readonly("previous_declaration", &CXXRecordDecl::PreviousDeclaration)
    .def_property_readonly("template_instantiation_pattern", &CXXRecordDecl::TemplateInstantiationPattern)
    .def_property_readonly("template_specialization_kind", &CXXRecordDecl::TemplateSpecializationKind)
    .def_property_readonly("has_any_dependent_bases", &CXXRecordDecl::HasAnyDependentBases)
    .def_property_readonly("has_constexpr_default_constructor", &CXXRecordDecl::HasConstexprDefaultConstructor)
    .def_property_readonly("has_constexpr_destructor", &CXXRecordDecl::HasConstexprDestructor)
    .def_property_readonly("has_constexpr_non_copy_move_constructor", &CXXRecordDecl::HasConstexprNonCopyMoveConstructor)
    .def_property_readonly("has_copy_assignment_with_const_parameter", &CXXRecordDecl::HasCopyAssignmentWithConstParameter)
    .def_property_readonly("has_copy_constructor_with_const_parameter", &CXXRecordDecl::HasCopyConstructorWithConstParameter)
    .def_property_readonly("has_default_constructor", &CXXRecordDecl::HasDefaultConstructor)
    .def_property_readonly("has_definition", &CXXRecordDecl::HasDefinition)
    .def_property_readonly("has_direct_fields", &CXXRecordDecl::HasDirectFields)
    .def_property_readonly("has_friends", &CXXRecordDecl::HasFriends)
    .def_property_readonly("has_in_class_initializer", &CXXRecordDecl::HasInClassInitializer)
    .def_property_readonly("has_inherited_assignment", &CXXRecordDecl::HasInheritedAssignment)
    .def_property_readonly("has_inherited_constructor", &CXXRecordDecl::HasInheritedConstructor)
    .def_property_readonly("has_initializer_method", &CXXRecordDecl::HasInitializerMethod)
    .def_property_readonly("has_irrelevant_destructor", &CXXRecordDecl::HasIrrelevantDestructor)
    .def_property_readonly("has_known_lambda_internal_linkage", &CXXRecordDecl::HasKnownLambdaInternalLinkage)
    .def_property_readonly("has_move_assignment", &CXXRecordDecl::HasMoveAssignment)
    .def_property_readonly("has_move_constructor", &CXXRecordDecl::HasMoveConstructor)
    .def_property_readonly("has_mutable_fields", &CXXRecordDecl::HasMutableFields)
    .def_property_readonly("has_non_literal_type_fields_or_bases", &CXXRecordDecl::HasNonLiteralTypeFieldsOrBases)
    .def_property_readonly("has_non_trivial_copy_assignment", &CXXRecordDecl::HasNonTrivialCopyAssignment)
    .def_property_readonly("has_non_trivial_copy_constructor", &CXXRecordDecl::HasNonTrivialCopyConstructor)
    .def_property_readonly("has_non_trivial_copy_constructor_for_call", &CXXRecordDecl::HasNonTrivialCopyConstructorForCall)
    .def_property_readonly("has_non_trivial_default_constructor", &CXXRecordDecl::HasNonTrivialDefaultConstructor)
    .def_property_readonly("has_non_trivial_destructor", &CXXRecordDecl::HasNonTrivialDestructor)
    .def_property_readonly("has_non_trivial_destructor_for_call", &CXXRecordDecl::HasNonTrivialDestructorForCall)
    .def_property_readonly("has_non_trivial_move_assignment", &CXXRecordDecl::HasNonTrivialMoveAssignment)
    .def_property_readonly("has_non_trivial_move_constructor", &CXXRecordDecl::HasNonTrivialMoveConstructor)
    .def_property_readonly("has_non_trivial_move_constructor_for_call", &CXXRecordDecl::HasNonTrivialMoveConstructorForCall)
    .def_property_readonly("has_private_fields", &CXXRecordDecl::HasPrivateFields)
    .def_property_readonly("has_protected_fields", &CXXRecordDecl::HasProtectedFields)
    .def_property_readonly("has_simple_copy_assignment", &CXXRecordDecl::HasSimpleCopyAssignment)
    .def_property_readonly("has_simple_copy_constructor", &CXXRecordDecl::HasSimpleCopyConstructor)
    .def_property_readonly("has_simple_destructor", &CXXRecordDecl::HasSimpleDestructor)
    .def_property_readonly("has_simple_move_assignment", &CXXRecordDecl::HasSimpleMoveAssignment)
    .def_property_readonly("has_simple_move_constructor", &CXXRecordDecl::HasSimpleMoveConstructor)
    .def_property_readonly("has_trivial_copy_assignment", &CXXRecordDecl::HasTrivialCopyAssignment)
    .def_property_readonly("has_trivial_copy_constructor", &CXXRecordDecl::HasTrivialCopyConstructor)
    .def_property_readonly("has_trivial_copy_constructor_for_call", &CXXRecordDecl::HasTrivialCopyConstructorForCall)
    .def_property_readonly("has_trivial_default_constructor", &CXXRecordDecl::HasTrivialDefaultConstructor)
    .def_property_readonly("has_trivial_destructor", &CXXRecordDecl::HasTrivialDestructor)
    .def_property_readonly("has_trivial_destructor_for_call", &CXXRecordDecl::HasTrivialDestructorForCall)
    .def_property_readonly("has_trivial_move_assignment", &CXXRecordDecl::HasTrivialMoveAssignment)
    .def_property_readonly("has_trivial_move_constructor", &CXXRecordDecl::HasTrivialMoveConstructor)
    .def_property_readonly("has_trivial_move_constructor_for_call", &CXXRecordDecl::HasTrivialMoveConstructorForCall)
    .def_property_readonly("has_uninitialized_reference_member", &CXXRecordDecl::HasUninitializedReferenceMember)
    .def_property_readonly("has_user_declared_constructor", &CXXRecordDecl::HasUserDeclaredConstructor)
    .def_property_readonly("has_user_declared_copy_assignment", &CXXRecordDecl::HasUserDeclaredCopyAssignment)
    .def_property_readonly("has_user_declared_copy_constructor", &CXXRecordDecl::HasUserDeclaredCopyConstructor)
    .def_property_readonly("has_user_declared_destructor", &CXXRecordDecl::HasUserDeclaredDestructor)
    .def_property_readonly("has_user_declared_move_assignment", &CXXRecordDecl::HasUserDeclaredMoveAssignment)
    .def_property_readonly("has_user_declared_move_constructor", &CXXRecordDecl::HasUserDeclaredMoveConstructor)
    .def_property_readonly("has_user_declared_move_operation", &CXXRecordDecl::HasUserDeclaredMoveOperation)
    .def_property_readonly("has_user_provided_default_constructor", &CXXRecordDecl::HasUserProvidedDefaultConstructor)
    .def_property_readonly("has_variant_members", &CXXRecordDecl::HasVariantMembers)
    .def_property_readonly("implicit_copy_assignment_has_const_parameter", &CXXRecordDecl::ImplicitCopyAssignmentHasConstParameter)
    .def_property_readonly("implicit_copy_constructor_has_const_parameter", &CXXRecordDecl::ImplicitCopyConstructorHasConstParameter)
    .def_property_readonly("is_abstract", &CXXRecordDecl::IsAbstract)
    .def_property_readonly("is_aggregate", &CXXRecordDecl::IsAggregate)
    .def_property_readonly("is_any_destructor_no_return", &CXXRecordDecl::IsAnyDestructorNoReturn)
    .def_property_readonly("is_c_like", &CXXRecordDecl::IsCLike)
    .def_property_readonly("is_cxx11_standard_layout", &CXXRecordDecl::IsCXX11StandardLayout)
    .def_property_readonly("is_dependent_lambda", &CXXRecordDecl::IsDependentLambda)
    .def_property_readonly("is_dynamic_class", &CXXRecordDecl::IsDynamicClass)
    .def_property_readonly("is_effectively_final", &CXXRecordDecl::IsEffectivelyFinal)
    .def_property_readonly("is_empty", &CXXRecordDecl::IsEmpty)
    .def_property_readonly("is_generic_lambda", &CXXRecordDecl::IsGenericLambda)
    .def_property_readonly("is_interface_like", &CXXRecordDecl::IsInterfaceLike)
    .def_property_readonly("is_lambda", &CXXRecordDecl::IsLambda)
    .def_property_readonly("is_literal", &CXXRecordDecl::IsLiteral)
    .def_property_readonly("is_local_class", &CXXRecordDecl::IsLocalClass)
    .def_property_readonly("is_never_dependent_lambda", &CXXRecordDecl::IsNeverDependentLambda)
    .def_property_readonly("is_pod", &CXXRecordDecl::IsPOD)
    .def_property_readonly("is_parsing_base_specifiers", &CXXRecordDecl::IsParsingBaseSpecifiers)
    .def_property_readonly("is_polymorphic", &CXXRecordDecl::IsPolymorphic)
    .def_property_readonly("is_standard_layout", &CXXRecordDecl::IsStandardLayout)
    .def_property_readonly("is_structural", &CXXRecordDecl::IsStructural)
    .def_property_readonly("is_trivial", &CXXRecordDecl::IsTrivial)
    .def_property_readonly("is_trivially_copyable", &CXXRecordDecl::IsTriviallyCopyable)
    .def_property_readonly("lambda_is_default_constructible_and_assignable", &CXXRecordDecl::LambdaIsDefaultConstructibleAndAssignable)
    .def_property_readonly("may_be_abstract", &CXXRecordDecl::MayBeAbstract)
    .def_property_readonly("may_be_dynamic_class", &CXXRecordDecl::MayBeDynamicClass)
    .def_property_readonly("may_be_non_dynamic_class", &CXXRecordDecl::MayBeNonDynamicClass)
    .def_property_readonly("methods", &CXXRecordDecl::Methods)
    .def_property_readonly("needs_implicit_copy_assignment", &CXXRecordDecl::NeedsImplicitCopyAssignment)
    .def_property_readonly("needs_implicit_copy_constructor", &CXXRecordDecl::NeedsImplicitCopyConstructor)
    .def_property_readonly("needs_implicit_default_constructor", &CXXRecordDecl::NeedsImplicitDefaultConstructor)
    .def_property_readonly("needs_implicit_destructor", &CXXRecordDecl::NeedsImplicitDestructor)
    .def_property_readonly("needs_implicit_move_assignment", &CXXRecordDecl::NeedsImplicitMoveAssignment)
    .def_property_readonly("needs_implicit_move_constructor", &CXXRecordDecl::NeedsImplicitMoveConstructor)
    .def_property_readonly("needs_overload_resolution_for_copy_assignment", &CXXRecordDecl::NeedsOverloadResolutionForCopyAssignment)
    .def_property_readonly("needs_overload_resolution_for_copy_constructor", &CXXRecordDecl::NeedsOverloadResolutionForCopyConstructor)
    .def_property_readonly("needs_overload_resolution_for_destructor", &CXXRecordDecl::NeedsOverloadResolutionForDestructor)
    .def_property_readonly("needs_overload_resolution_for_move_assignment", &CXXRecordDecl::NeedsOverloadResolutionForMoveAssignment)
    .def_property_readonly("needs_overload_resolution_for_move_constructor", &CXXRecordDecl::NeedsOverloadResolutionForMoveConstructor)
    .def_property_readonly("null_field_offset_is_zero", &CXXRecordDecl::NullFieldOffsetIsZero)
    .def_property_readonly("virtual_bases", &CXXRecordDecl::VirtualBases);
}
} // namespace pasta
