/*
 * Copyright (c) 2023 Trail of Bits, Inc.
 */

// This file is auto-generated.

#include <pasta/AST/AST.h>
#include <pasta/AST/Attr.h>
#include <pasta/AST/Decl.h>
#include <pasta/AST/Stmt.h>
#include <pasta/AST/Type.h>

#include <pybind11/pybind11.h>

namespace pasta {
namespace py = pybind11;

void RegisterCXXRecordDecl(py::module_ &m) {
  py::class_<CXXRecordDecl, Decl, NamedDecl, RecordDecl, TagDecl, TypeDecl>(m, "CXXRecordDecl")
    .def_property_readonly("AllowConstDefaultInitializer", &CXXRecordDecl::AllowConstDefaultInitializer)
    .def_property_readonly("Bases", &CXXRecordDecl::Bases)
    .def_property_readonly("CalculateInheritanceModel", &CXXRecordDecl::CalculateInheritanceModel)
    .def_property_readonly("Constructors", &CXXRecordDecl::Constructors)
    .def_property_readonly("DefaultedCopyConstructorIsDeleted", &CXXRecordDecl::DefaultedCopyConstructorIsDeleted)
    .def_property_readonly("DefaultedDefaultConstructorIsConstexpr", &CXXRecordDecl::DefaultedDefaultConstructorIsConstexpr)
    .def_property_readonly("DefaultedDestructorIsConstexpr", &CXXRecordDecl::DefaultedDestructorIsConstexpr)
    .def_property_readonly("DefaultedDestructorIsDeleted", &CXXRecordDecl::DefaultedDestructorIsDeleted)
    .def_property_readonly("DefaultedMoveConstructorIsDeleted", &CXXRecordDecl::DefaultedMoveConstructorIsDeleted)
    .def_property_readonly("Friends", &CXXRecordDecl::Friends)
    .def_property_readonly("CanonicalDeclaration", &CXXRecordDecl::CanonicalDeclaration)
    .def_property_readonly("Definition", &CXXRecordDecl::Definition)
    .def_property_readonly("DependentLambdaCallOperator", &CXXRecordDecl::DependentLambdaCallOperator)
    .def_property_readonly("DescribedClassTemplate", &CXXRecordDecl::DescribedClassTemplate)
    .def_property_readonly("Destructor", &CXXRecordDecl::Destructor)
    .def_property_readonly("DeviceLambdaManglingNumber", &CXXRecordDecl::DeviceLambdaManglingNumber)
    .def_property_readonly("GenericLambdaTemplateParameterList", &CXXRecordDecl::GenericLambdaTemplateParameterList)
    .def_property_readonly("InstantiatedFromMemberClass", &CXXRecordDecl::InstantiatedFromMemberClass)
    .def_property_readonly("LambdaCallOperator", &CXXRecordDecl::LambdaCallOperator)
    .def_property_readonly("LambdaCaptureDefault", &CXXRecordDecl::LambdaCaptureDefault)
    .def_property_readonly("LambdaContextDeclaration", &CXXRecordDecl::LambdaContextDeclaration)
    .def_property_readonly("LambdaDependencyKind", &CXXRecordDecl::LambdaDependencyKind)
    .def_property_readonly("LambdaExplicitTemplateParameters", &CXXRecordDecl::LambdaExplicitTemplateParameters)
    .def_property_readonly("LambdaManglingNumber", &CXXRecordDecl::LambdaManglingNumber)
    .def_property_readonly("LambdaType", &CXXRecordDecl::LambdaType)
    .def_property_readonly("MSInheritanceModel", &CXXRecordDecl::MSInheritanceModel)
    .def_property_readonly("MSVtorDispMode", &CXXRecordDecl::MSVtorDispMode)
    .def_property_readonly("MostRecentDeclaration", &CXXRecordDecl::MostRecentDeclaration)
    .def_property_readonly("MostRecentNonInjectedDeclaration", &CXXRecordDecl::MostRecentNonInjectedDeclaration)
    .def_property_readonly("NumBases", &CXXRecordDecl::NumBases)
    .def_property_readonly("NumVirtualBases", &CXXRecordDecl::NumVirtualBases)
    .def_property_readonly("ODRHash", &CXXRecordDecl::ODRHash)
    .def_property_readonly("PreviousDeclaration", &CXXRecordDecl::PreviousDeclaration)
    .def_property_readonly("TemplateInstantiationPattern", &CXXRecordDecl::TemplateInstantiationPattern)
    .def_property_readonly("TemplateSpecializationKind", &CXXRecordDecl::TemplateSpecializationKind)
    .def_property_readonly("HasAnyDependentBases", &CXXRecordDecl::HasAnyDependentBases)
    .def_property_readonly("HasConstexprDefaultConstructor", &CXXRecordDecl::HasConstexprDefaultConstructor)
    .def_property_readonly("HasConstexprDestructor", &CXXRecordDecl::HasConstexprDestructor)
    .def_property_readonly("HasConstexprNonCopyMoveConstructor", &CXXRecordDecl::HasConstexprNonCopyMoveConstructor)
    .def_property_readonly("HasCopyAssignmentWithConstParameter", &CXXRecordDecl::HasCopyAssignmentWithConstParameter)
    .def_property_readonly("HasCopyConstructorWithConstParameter", &CXXRecordDecl::HasCopyConstructorWithConstParameter)
    .def_property_readonly("HasDefaultConstructor", &CXXRecordDecl::HasDefaultConstructor)
    .def_property_readonly("HasDefinition", &CXXRecordDecl::HasDefinition)
    .def_property_readonly("HasDirectFields", &CXXRecordDecl::HasDirectFields)
    .def_property_readonly("HasFriends", &CXXRecordDecl::HasFriends)
    .def_property_readonly("HasInClassInitializer", &CXXRecordDecl::HasInClassInitializer)
    .def_property_readonly("HasInheritedAssignment", &CXXRecordDecl::HasInheritedAssignment)
    .def_property_readonly("HasInheritedConstructor", &CXXRecordDecl::HasInheritedConstructor)
    .def_property_readonly("HasInitializerMethod", &CXXRecordDecl::HasInitializerMethod)
    .def_property_readonly("HasIrrelevantDestructor", &CXXRecordDecl::HasIrrelevantDestructor)
    .def_property_readonly("HasKnownLambdaInternalLinkage", &CXXRecordDecl::HasKnownLambdaInternalLinkage)
    .def_property_readonly("HasMoveAssignment", &CXXRecordDecl::HasMoveAssignment)
    .def_property_readonly("HasMoveConstructor", &CXXRecordDecl::HasMoveConstructor)
    .def_property_readonly("HasMutableFields", &CXXRecordDecl::HasMutableFields)
    .def_property_readonly("HasNonLiteralTypeFieldsOrBases", &CXXRecordDecl::HasNonLiteralTypeFieldsOrBases)
    .def_property_readonly("HasNonTrivialCopyAssignment", &CXXRecordDecl::HasNonTrivialCopyAssignment)
    .def_property_readonly("HasNonTrivialCopyConstructor", &CXXRecordDecl::HasNonTrivialCopyConstructor)
    .def_property_readonly("HasNonTrivialCopyConstructorForCall", &CXXRecordDecl::HasNonTrivialCopyConstructorForCall)
    .def_property_readonly("HasNonTrivialDefaultConstructor", &CXXRecordDecl::HasNonTrivialDefaultConstructor)
    .def_property_readonly("HasNonTrivialDestructor", &CXXRecordDecl::HasNonTrivialDestructor)
    .def_property_readonly("HasNonTrivialDestructorForCall", &CXXRecordDecl::HasNonTrivialDestructorForCall)
    .def_property_readonly("HasNonTrivialMoveAssignment", &CXXRecordDecl::HasNonTrivialMoveAssignment)
    .def_property_readonly("HasNonTrivialMoveConstructor", &CXXRecordDecl::HasNonTrivialMoveConstructor)
    .def_property_readonly("HasNonTrivialMoveConstructorForCall", &CXXRecordDecl::HasNonTrivialMoveConstructorForCall)
    .def_property_readonly("HasPrivateFields", &CXXRecordDecl::HasPrivateFields)
    .def_property_readonly("HasProtectedFields", &CXXRecordDecl::HasProtectedFields)
    .def_property_readonly("HasSimpleCopyAssignment", &CXXRecordDecl::HasSimpleCopyAssignment)
    .def_property_readonly("HasSimpleCopyConstructor", &CXXRecordDecl::HasSimpleCopyConstructor)
    .def_property_readonly("HasSimpleDestructor", &CXXRecordDecl::HasSimpleDestructor)
    .def_property_readonly("HasSimpleMoveAssignment", &CXXRecordDecl::HasSimpleMoveAssignment)
    .def_property_readonly("HasSimpleMoveConstructor", &CXXRecordDecl::HasSimpleMoveConstructor)
    .def_property_readonly("HasTrivialCopyAssignment", &CXXRecordDecl::HasTrivialCopyAssignment)
    .def_property_readonly("HasTrivialCopyConstructor", &CXXRecordDecl::HasTrivialCopyConstructor)
    .def_property_readonly("HasTrivialCopyConstructorForCall", &CXXRecordDecl::HasTrivialCopyConstructorForCall)
    .def_property_readonly("HasTrivialDefaultConstructor", &CXXRecordDecl::HasTrivialDefaultConstructor)
    .def_property_readonly("HasTrivialDestructor", &CXXRecordDecl::HasTrivialDestructor)
    .def_property_readonly("HasTrivialDestructorForCall", &CXXRecordDecl::HasTrivialDestructorForCall)
    .def_property_readonly("HasTrivialMoveAssignment", &CXXRecordDecl::HasTrivialMoveAssignment)
    .def_property_readonly("HasTrivialMoveConstructor", &CXXRecordDecl::HasTrivialMoveConstructor)
    .def_property_readonly("HasTrivialMoveConstructorForCall", &CXXRecordDecl::HasTrivialMoveConstructorForCall)
    .def_property_readonly("HasUninitializedReferenceMember", &CXXRecordDecl::HasUninitializedReferenceMember)
    .def_property_readonly("HasUserDeclaredConstructor", &CXXRecordDecl::HasUserDeclaredConstructor)
    .def_property_readonly("HasUserDeclaredCopyAssignment", &CXXRecordDecl::HasUserDeclaredCopyAssignment)
    .def_property_readonly("HasUserDeclaredCopyConstructor", &CXXRecordDecl::HasUserDeclaredCopyConstructor)
    .def_property_readonly("HasUserDeclaredDestructor", &CXXRecordDecl::HasUserDeclaredDestructor)
    .def_property_readonly("HasUserDeclaredMoveAssignment", &CXXRecordDecl::HasUserDeclaredMoveAssignment)
    .def_property_readonly("HasUserDeclaredMoveConstructor", &CXXRecordDecl::HasUserDeclaredMoveConstructor)
    .def_property_readonly("HasUserDeclaredMoveOperation", &CXXRecordDecl::HasUserDeclaredMoveOperation)
    .def_property_readonly("HasUserProvidedDefaultConstructor", &CXXRecordDecl::HasUserProvidedDefaultConstructor)
    .def_property_readonly("HasVariantMembers", &CXXRecordDecl::HasVariantMembers)
    .def_property_readonly("ImplicitCopyAssignmentHasConstParameter", &CXXRecordDecl::ImplicitCopyAssignmentHasConstParameter)
    .def_property_readonly("ImplicitCopyConstructorHasConstParameter", &CXXRecordDecl::ImplicitCopyConstructorHasConstParameter)
    .def_property_readonly("IsAbstract", &CXXRecordDecl::IsAbstract)
    .def_property_readonly("IsAggregate", &CXXRecordDecl::IsAggregate)
    .def_property_readonly("IsAnyDestructorNoReturn", &CXXRecordDecl::IsAnyDestructorNoReturn)
    .def_property_readonly("IsCLike", &CXXRecordDecl::IsCLike)
    .def_property_readonly("IsCXX11StandardLayout", &CXXRecordDecl::IsCXX11StandardLayout)
    .def_property_readonly("IsDependentLambda", &CXXRecordDecl::IsDependentLambda)
    .def_property_readonly("IsDynamicClass", &CXXRecordDecl::IsDynamicClass)
    .def_property_readonly("IsEffectivelyFinal", &CXXRecordDecl::IsEffectivelyFinal)
    .def_property_readonly("IsEmpty", &CXXRecordDecl::IsEmpty)
    .def_property_readonly("IsGenericLambda", &CXXRecordDecl::IsGenericLambda)
    .def_property_readonly("IsInterfaceLike", &CXXRecordDecl::IsInterfaceLike)
    .def_property_readonly("IsLambda", &CXXRecordDecl::IsLambda)
    .def_property_readonly("IsLiteral", &CXXRecordDecl::IsLiteral)
    .def_property_readonly("IsLocalClass", &CXXRecordDecl::IsLocalClass)
    .def_property_readonly("IsNeverDependentLambda", &CXXRecordDecl::IsNeverDependentLambda)
    .def_property_readonly("IsPOD", &CXXRecordDecl::IsPOD)
    .def_property_readonly("IsParsingBaseSpecifiers", &CXXRecordDecl::IsParsingBaseSpecifiers)
    .def_property_readonly("IsPolymorphic", &CXXRecordDecl::IsPolymorphic)
    .def_property_readonly("IsStandardLayout", &CXXRecordDecl::IsStandardLayout)
    .def_property_readonly("IsStructural", &CXXRecordDecl::IsStructural)
    .def_property_readonly("IsTrivial", &CXXRecordDecl::IsTrivial)
    .def_property_readonly("IsTriviallyCopyable", &CXXRecordDecl::IsTriviallyCopyable)
    .def_property_readonly("LambdaIsDefaultConstructibleAndAssignable", &CXXRecordDecl::LambdaIsDefaultConstructibleAndAssignable)
    .def_property_readonly("MayBeAbstract", &CXXRecordDecl::MayBeAbstract)
    .def_property_readonly("MayBeDynamicClass", &CXXRecordDecl::MayBeDynamicClass)
    .def_property_readonly("MayBeNonDynamicClass", &CXXRecordDecl::MayBeNonDynamicClass)
    .def_property_readonly("Methods", &CXXRecordDecl::Methods)
    .def_property_readonly("NeedsImplicitCopyAssignment", &CXXRecordDecl::NeedsImplicitCopyAssignment)
    .def_property_readonly("NeedsImplicitCopyConstructor", &CXXRecordDecl::NeedsImplicitCopyConstructor)
    .def_property_readonly("NeedsImplicitDefaultConstructor", &CXXRecordDecl::NeedsImplicitDefaultConstructor)
    .def_property_readonly("NeedsImplicitDestructor", &CXXRecordDecl::NeedsImplicitDestructor)
    .def_property_readonly("NeedsImplicitMoveAssignment", &CXXRecordDecl::NeedsImplicitMoveAssignment)
    .def_property_readonly("NeedsImplicitMoveConstructor", &CXXRecordDecl::NeedsImplicitMoveConstructor)
    .def_property_readonly("NeedsOverloadResolutionForCopyAssignment", &CXXRecordDecl::NeedsOverloadResolutionForCopyAssignment)
    .def_property_readonly("NeedsOverloadResolutionForCopyConstructor", &CXXRecordDecl::NeedsOverloadResolutionForCopyConstructor)
    .def_property_readonly("NeedsOverloadResolutionForDestructor", &CXXRecordDecl::NeedsOverloadResolutionForDestructor)
    .def_property_readonly("NeedsOverloadResolutionForMoveAssignment", &CXXRecordDecl::NeedsOverloadResolutionForMoveAssignment)
    .def_property_readonly("NeedsOverloadResolutionForMoveConstructor", &CXXRecordDecl::NeedsOverloadResolutionForMoveConstructor)
    .def_property_readonly("NullFieldOffsetIsZero", &CXXRecordDecl::NullFieldOffsetIsZero)
    .def_property_readonly("VirtualBases", &CXXRecordDecl::VirtualBases);
}
} // namespace pasta
